language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.3
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
script:
    - gradle checkstyle
    - gradle lint
    - gradle pmd
    - gradle test